@startuml

entity Employee {
    Id : Guid
    --
    ApplicationUser : ApplicationUser
    ' EmployeeKeyCodePlaceholder
    --
    Email : string
    ' EmployeePropertyCodePlaceholder
}

' EntityCodePlaceholder

Employee |o--o| ApplicationUser
' RelationshipCodePlaceholder

@enduml
